#!/usr/bin/env bash

# generic apps that have the same installation on all systems

# python
pip3 install --user -U \
    flake8 \
    sphinx

# xonsh
pip3 install --user -U xonsh gitsome \
    pillow gnureadline \
    xontrib-autojump xonsh-docker-tabcomplete xontrib-readable-traceback \
    git+https://github.com/laloch/xonsh-vox-tabcomplete.git@proxy-warnings \
    git+https://github.com/deeuu/xontrib-apipenv.git
