#!/usr/bin/env bash

# generic apps that have the same installation on all systems

# python
pip3 install --user -U \
    flake8 \
    sphinx \
    pillow \
    gnureadline

# pyls and flake8 support
pip3 install --user 'python-language-server[all]' git+https://github.com/emanspeaks/pyls-flake8

# xonsh
pip3 install --user -U gitsome \
    xontrib-autojump xonsh-docker-tabcomplete xontrib-readable-traceback \
    git+https://github.com/laloch/xonsh-vox-tabcomplete.git@proxy-warnings \
    git+https://github.com/deeuu/xontrib-apipenv.git \
    xonsh
