#!/usr/bin/env bash

# generic apps that have the same installation on all systems

# python
pip3 install --user -U \
    cython \
    gnureadline \
    flake8 \
    isort \
    jedi \
    nose \
    pillow \
    pipenv \
    pytest \
    sphinx

# beets and mpd stuff
pip3 install --user -U beets python-mpd2 discogs-client pyacoustid

# xonsh

pip3 install --user -U \
    xonsh-docker-tabcomplete \
    xontrib-readable-traceback \
    xontrib-avox \
    xonsh-vox-tabcomplete \
    xontrib-z \
    xonsh
