#!/usr/bin/env bash

sudo add-apt-repository -y --no-update ppa:mmstick76/alacritty
sudo add-apt-repository -y --no-update ppa:kelleyk/emacs

sudo apt-get update

sudo apt-get install alacritty || echo "Alacritty not installed!"

sudo apt-get install -y \
    autojump \
    cargo \
    emacs26 \
    libncurses-dev \
    libcanberra-gtk-module libcanberra-gtk3-module \
    libjpeg-dev libtiff-dev libjpeg-dev zlib1g-dev \
    libfreetype6-dev liblcms2-dev libwebp-dev \
    python3-dev \
    python3-numpy \
    python3-pip \
    python3-venv

# common installs (pip, etc)
./common

# nerd fonts
if [[ ! -f "$HOME/.fonts/Fura Code Bold Nerd Font Complete Mono.otf" ]]; then
    wget https://github.com/ryanoasis/nerd-fonts/releases/download/v2.0.0/FiraCode.zip -O - | python -c "import zipfile,sys,StringIO;zipfile.ZipFile(StringIO.StringIO(sys.stdin.read())).extractall(sys.argv[1] if len(sys.argv) == 2 else '.')" ~/.fonts

    fc-cache -fv
fi
