#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# make sure we are in the directory of the script so relative paths work
cd "$DIR" || exit

mkdir -p ~/.fonts

# don't need since we're only booting one thing (and zfs errors out)
# See: https://github.com/openzfs/zfs/discussions/9801
sudo apt remove -y os-prober

# for add-apt-repository
sudo apt install software-properties-common

# fix secure boot
sudo cp /boot/efi/EFI/ubuntu/{grubx64,shimx64}.efi
cp grubx64.efi shimx64.efi
sudo apt remove -y --purge shim shim-signed
sudo update-grub
# just in case
sudo cp /boot/efi/EFI/ubuntu/{grubx64,shimx64}.efi

# recent-ish emacs
sudo add-apt-repository -y --no-update ppa:kelleyk/emacs

# ugh, node
curl -fsSL https://deb.nodesource.com/setup_15.x | sudo -E bash -

sudo apt-get update

sudo apt-get install -y \
    ansible \
    autojump \
    autokey-gtk \
    cargo \
    cmake \
    fd-find \
    editorconfig \
    emacs27 \
    gcc \
    git \
    glslang-tools \
    gnuplot \
    graphviz \
    jq \
    libncurses-dev \
    libjpeg-dev libtiff-dev libjpeg-dev zlib1g-dev \
    libfreetype6-dev liblcms2-dev libwebp-dev \
    libopenblas-dev \
    libtool \
    libtool-bin \
    libzmq3-dev \
    markdown \
    nautilus-nextcloud \
    nextcloud-desktop \
    nvidia-driver-460 \
    nvidia-cuda-toolkit \
    nodejs \
    openssh-server \
    python3-dev \
    python3-numpy \
    python3-pip \
    python3-venv \
    ripgrep \
    shellcheck \
    sqlite3

npm install -g js-beautify stylelint
npm install -g @bitwarden/cli

# common installs (pip, etc)
./common

# nerd fonts
if [[ ! -f "$HOME/.fonts/Fura Code Bold Nerd Font Complete Mono.otf" ]]; then
    wget https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/FiraCode.zip -O - | busybox unzip -d ~/.fonts -
fi

# all-the-icons and friends
cp fonts/*.ttf ~/.fonts
fc-cache -fv

