#!/bin/sh

system_type=$(uname -s)
is_sudo=$(sh -c "sudo -vn 2>&1 && echo password" | grep -c password)
local_hostname=$(scutil --get LocalHostName 2>/dev/null)

if [ "$system_type" = "Darwin" ] && [ $is_sudo = 1 ]; then

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi

  echo "Installing homebrew packages"
  # gawk is left out because it conflicts with emacs-plus
  brew bundle -v --no-lock --file=/dev/stdin <<EOF
tap "d12frosted/emacs-plus"
tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/command-not-found"
tap "homebrew/services"
brew "rlwrap"
brew "act"
brew "pango"
brew "librsvg"
brew "openssl@3"
brew "ansible"
brew "aspell"
brew "automake"
brew "bear"
brew "binutils"
brew "node"
brew "bitwarden-cli"
brew "boost"
brew "gcc"
brew "hwloc"
brew "bzip2"
brew "ccache"
brew "openblas"
brew "libomp"
brew "sdl2"
brew "ffmpeg"
brew "chromaprint"
brew "clang-format"
brew "cloc"
brew "cmake"
brew "cmake-docs"
brew "cookiecutter"
brew "coreutils"
brew "gnupg"
brew "poppler"
brew "diff-pdf"
brew "difftastic"
brew "editorconfig"
brew "enchant"
brew "fd"
brew "fdupes"
brew "fftw"
brew "findutils"
brew "gawk"
brew "git"
brew "git-absorb"
brew "git-lfs"
brew "pkg-config"
brew "gzip"
brew "inetutils"
brew "ipython"
brew "isync"
brew "jq"
brew "languagetool"
brew "latexindent"
brew "libffi"
brew "libgccjit"
brew "libolm"
brew "libvirt"
brew "libvterm"
brew "libxml2"
brew "libxmlsec1"
brew "libzip"
brew "llm"
brew "llvm"
brew "luajit"
brew "man-db"
brew "mas"
brew "mdv"
brew "mercurial"
brew "ninja"
brew "meson"
brew "mkcert"
brew "pugixml"
brew "mkvtoolnix"
brew "mp3gain"
brew "mp3val"
brew "mpi4py"
brew "xapian"
brew "mu"
brew "p7zip"
brew "pandoc"
brew "pdf2svg"
brew "pinentry-mac"
brew "pngpaste"
brew "podman"
brew "podman-compose"
brew "pre-commit"
brew "ripgrep"
brew "rsync"
brew "ruff"
brew "ruff-lsp"
brew "rust"
brew "rust-analyzer"
brew "rustc-completion"
brew "rustfmt"
brew "shellcheck"
brew "tectonic"
brew "texinfo"
brew "tree"
brew "tree-sitter"
brew "watchman"
brew "wget"
brew "wordnet"
brew "xdg-ninja"
brew "yadm"
brew "yamllint"
brew "zlib-ng"
brew "d12frosted/emacs-plus/emacs-plus@29", args: ["with-dbus", "with-elrumo1-icon", "with-native-comp", "with-no-frame-refocus", "with-poll", "with-xwidgets"]
cask "appcleaner"
cask "balenaetcher"
cask "firefox"
cask "firefox-developer-edition"
cask "font-fontawesome"
cask "font-ibm-plex-mono"
cask "font-inconsolata-nerd-font"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "font-jsmath-cmbx10"
cask "grandperspective"
cask "hammerspoon"
cask "karabiner-elements"
cask "mysides"
cask "nextcloud"
cask "podman-desktop"
cask "rar"
cask "stats"
cask "tailscale"
cask "temurin"
cask "tex-live-utility"
cask "vlc"
cask "xquartz"
EOF

# start hammerspoon at login
osascript -e 'tell application "System Events" to make login item at end with properties {path:"/Applications/Hammerspoon.app", hidden:false}' &> /dev/null

# start nextcloud at login
osascript -e 'tell application "System Events" to make login item at end with properties {path:"/Applications/Nextcloud.app", hidden:false}' &> /dev/null

# open so that we can grant permissions
open -a Karabiner-Elements
open -a Stats
open -a Hammerspoon

fi
