(package! ace-mc)
(package! exec-path-from-shell :disable t)
(package! banner-comment)
(package! bitwarden :recipe (:host github :repo "seanfarley/emacs-bitwarden"))
(package! col-highlight :recipe (:host github :repo "emacsmirror/col-highlight"))
(package! color-identifiers-mode)
(package! dot-mode)
(package! embrace)
(package! emr)
(package! fancy-narrow)
(package! focus)
(package! github-review)
(package! goto-chg)
(package! lispy)
(package! mu4e-alert)
(package! mu4e-patch :recipe (:host github :repo "seanfarley/mu4e-patch"))
(package! org-ref)
(package! persistent-scratch)
(package! resize-window)
(package! ripgrep)
(package! srefactor)
(package! unfill)
(package! webpaste)
(package! whole-line-or-region)
(package! which-key-posframe)
(package! xonsh-mode :recipe (:host github :repo "seanfarley/xonsh-mode"))
