(package! exec-path-from-shell :disable t)
(package! banner-comment)
(package! bitwarden :recipe (:fetcher github :repo "seanfarley/emacs-bitwarden"))
(package! color-identifiers-mode)
(package! embrace)
(package! emr)
(package! focus)
(package! goto-chg)
(package! lispy)
(package! lsp-python-ms)
(package! mu4e-alert)
(package! mu4e-patch :recipe (:fetcher github :repo "seanfarley/mu4e-patch"))
(package! org-starter)
(package! persistent-scratch)
(package! resize-window)
(package! ripgrep)
(package! srefactor)
(package! unfill)
(package! webpaste)
(package! whole-line-or-region)
