(package! exec-path-from-shell :disable t)
(package! banner-comment)
(package! bitwarden :recipe (:fetcher github :repo "seanfarley/emacs-bitwarden"))
(package! emr)
(package! goto-chg)
(package! ivy-rich)
(package! lispy)
(package! mu4e-alert)
(package! mu4e-patch :recipe (:fetcher github :repo "seanfarley/mu4e-patch"))
(package! org-starter)
(package! persistent-scratch)
(package! resize-window)
(package! smart-jump)
(package! srefactor)
(package! unfill)
(package! whole-line-or-region)
