directory: ~/Music/beets
library:   ~/Music/beets/library.db
pluginpath: ~/Music/beets/BeetsPlugins
threaded: yes

ui:
  color: yes

paths:
  default: $albumartist/$year - $album/$track $title
  singleton: Non-Album/$artist/$title
  comp: Compilations/$album/$track $title

import:
  # write metadata to music files
  write: yes

  # move imported files from source to the music directory
  move: yes
  copy: no
  delete: no
  resume: ask
  log: ~/Music/beets/beets.log

  # use auto-tagging where possible
  # do not require confirmation on strong matches
  autotag: yes
  timid: no

match:
  strong_rec_thresh: 0.04
  preferred:
    countries: ['US', 'GB|UK']
    original_year: yes

# plugins

plugins: [
  bareasc,
  # bruteforce,
  convert,
  edit,
  embedart,
  fetchart,
  fromfilename,
  ftintitle,
  fuzzy,
  hook,
  info,
  lyrics,
  mbsync,
  missing,
  replaygain,
  smartplaylist,
  unimported,
]

embedart:
  auto: yes
  compare_threshold: 0
  remove_art_file: yes
  maxwidth: 500

ftintitle:
  auto: yes

replaygain:
  auto: yes
  overwrite: yes
  albumgain: yes

smartplaylist:
  playlist_dir: ~/Music/playlists
  playlists:
    - name: all.m3u
      query: ''

unimported:
    ignore_extensions: jpg png db DS_Store log
    ignore_subdirectories: NonMusic data temp

# hooks

hook:
  hooks:
    - event: import
      command: echo 'Now, import the new music into iTunes':' open ~/Music/playlists/*.m3u'

    # # automatically import new songs into iTunes; unfortunately this has two
    # # shortcomings: 1) it open iTunes and the music starts playing; 2) it
    # # doesn't add the new songs aren't written to the all.m3u file just yet
    # - event: import
    #   command: bash -c "open {lib.directory}/../playlists/*.m3u"
